import json
import os

class GenerationAgent:
    """
    생성/관리 에이전트: 
    1) 라이브러리에 있는 컴포넌트는 즉시 반환 (캐싱/사전 정의)
    2) 없는 컴포넌트는 LLM을 통해 최소 단위(Atomic)로 동적 생성 후 라이브러리에 저장.
    """
    def __init__(self):
        self.name = "GenerationAgent"
        # 절대 경로 처리 (orchestrator 실행 기준)
        base_dir = os.path.dirname(os.path.abspath(__file__))
        self.library_path = os.path.join(base_dir, "library", "components")

        # MVP 테스트용 하드코딩된 모의 LLM 응답기
        self._mock_llm_responses = {
            "text_input": {
                "type": "component",
                "name": "text_input",
                "html_template": "<input type=\"text\" class=\"border p-2 rounded w-full\" placeholder=\"{placeholder}\" />",
                "required_params": ["placeholder"],
                "description": "A dynamic text input generated by LLM."
            },
            "custom_graph": {
                "type": "component",
                "name": "custom_graph",
                "html_template": "<div class=\"w-full h-32 bg-gray-200 border-2 border-dashed border-gray-400 flex items-center justify-center\"><span class=\"text-gray-500\">Dynamic Graph Area for {data_type}</span></div>",
                "required_params": ["data_type"],
                "description": "A dynamically generated atomic graph placeholder."
            }
        }

    def load_component_metadata(self, component_name: str) -> dict:
        file_path = os.path.join(self.library_path, f"{component_name}.json")
        
        # 1. 라이브러리(캐시) 확인 로직
        if os.path.exists(file_path):
            print(f"[{self.name}] 🟢 라이브러리 히트: '{component_name}' (사전 컴포넌트 로드)")
            with open(file_path, 'r', encoding='utf-8') as f:
                return json.load(f)
                
        # 2. 동적 생성 (Atomic Component) 로직
        print(f"[{self.name}] 🟡 라이브러리 미스: '{component_name}' (LLM 최소 단위 동적 생성 시작)")
        
        # 실제로는 이곳에서 OpenAI API 등을 호출합니다.
        # [PROMPT] "UI 컴포넌트 이름 '{component_name}'에 대한 최소 단위의 HTML(Tailwind) 코드와 메타데이터 JSON 포맷을 만들어줘."
        dynamic_component = self._call_llm_for_atomic_component(component_name)
        
        # 3. 라이브러리에 저장 (캐싱)
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(dynamic_component, f, indent=4, ensure_ascii=False)
        print(f"[{self.name}] 💾 동적 컴포넌트 저장 완료: '{component_name}'")
        
        return dynamic_component

    def _call_llm_for_atomic_component(self, name: str) -> dict:
        """LLM 호출을 모방하는 함수 (MVP 용)"""
        if name in self._mock_llm_responses:
            return self._mock_llm_responses[name]
        
        # Fallback (전혀 모르는 컴포넌트일 경우)
        return {
            "type": "component",
            "name": name,
            "html_template": f"<div class=\"p-4 bg-yellow-100 border border-yellow-300\">Generated: {name} ({'{'}param{'}'})</div>",
            "required_params": ["param"],
            "description": f"Fallback LLM generated component for {name}."
        }
